### ISSUE TITLE
install man pages

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/osx-installer#66]

**Comment by ssokolenko** [comment]
Until the issue is resolved you can [build man pages manually][2] via a docker container using the supplied Dockerfile and then just copy generated files to `/usr/share/man/`:

    # Step 1: checkout docker sources, but make sure you do this
    # somewhere in /Users directory because boot2docker can only
    # share this path with docker containers
    git clone https://github.com/docker/docker.git
    
    # Step 2: build docker image  
    cd docker/docs/man
    docker build -t docker/md2man .
    
    # Step 3: build man pages
    docker run -v /Users/<path-to-git-dir>/docker/docs/man:/docs:rw \
    -w /docs -i docker/md2man /docs/md2man-all.sh

    # Step 4: copy generated man pages to /usr/share/man
    cp -R man* /usr/share/man/

Enjoy!

P.S. [Answered][2] at stackoverflow.

  [1]: https://github.com/docker/docker/blob/master/docs/man/README.md
  [2]: http://stackoverflow.com/a/29284046/131337

**Comment by spoon99** [comment]
+1

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
